spring.application.name=expense-tracker-api

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/expense_tracker_db?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Sudeep@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=${PORT:8080}
jwt.expiration=86400000
jwt.secret=${JWT_SECRET:zhB5F6TyfDRxFKejTd+vuUehK+QUWRXnkbfRtdGJZWo=}